### ISSUE TITLE
code about applications

### ISSUE THREAD

**Issue by anhquannguyen21** [ZhengdiYu/Arbitrary-Hands-3D-Reconstruction#13]
Thanks for your great work!
Can you release the code about your applications? I want to apply it to animation my 3D character on Blender.
Thanks.

**Comment by ZhengdiYu** [comment]
> Thanks for your great work! Can you release the code about your applications? I want to apply it to animation my 3D character on Blender. Thanks.

Thank you for your interest!

I think you could refer to [ROMP](https://github.com/Arthur151/ROMP/blob/master/romp/exports/blender_mocap.py) to adapt your own application code.
