### ISSUE TITLE
Questions about the table1 in your main paper?

### ISSUE THREAD

**Issue by julyiii** [ZhengdiYu/Arbitrary-Hands-3D-Reconstruction#16]
Thank you for your excellent work!
There are several questions that confused me lot about your experiment setting,   I hope you can clarify for me.
Q1:
In table 1, you show your result in both SH and IH test split,  Do you use the standard SH train set for training?  
Q2:
How do you get IntagHand result in SH split? It seems that intaghand is designed for only IH input, do you just use the hand results that actually appear in input image according to gt annotion for evaluation  while ignore the other side hand output?

**Comment by ZhengdiYu** [comment]
Thank you for your interest!

Q1: No, for the results in the table, we only use the IH test split. We also had experiments with mixing the SH and IH, which didn't show much difference.

Q2: Yes, we carefully adapt their code: I mask the other hand using the GT annotation (i.e. if there is only left hand annotation, we will mask the right hand.)

**Comment by julyiii** [comment]
Maybe you mean only use IH train split for train instead of IH test split?

**Comment by ZhengdiYu** [comment]
> Maybe you mean only use IH train split for train instead of IH test split?

Oh, sorry for the typo. Yes sure, we only use IH training split for training, and IH test split + SH test split for testing.
