### ISSUE TITLE
Which joints is used to align ?

### ISSUE THREAD

**Issue by julyiii** [ZhengdiYu/Arbitrary-Hands-3D-Reconstruction#17]
Which joints is used to align  when align both hands with the root joints?  The root joints is defined as  the wrist joint or the middle finger joint adjacent to the wrist?

**Comment by ZhengdiYu** [comment]
> Which joints is used to align when align both hands with the root joints? The root joints is defined as the wrist joint or the middle finger joint adjacent to the wrist?

We used the MCP joint of the middle finger follow previous work (e.g. [IntagHand](https://github.com/Dw1010/IntagHand/blob/5bb0775b176a6a72162f1750c0226165fbcaa2eb/apps/eval_interhand.py#L129), also see [here](https://github.com/BaowenZ/Two-Hand-Shape-Pose))

**Comment by julyiii** [comment]
That's to say, whether or not  use  gt scale information to rescale the predict joints, you all use the MCP joint of the middle finger as  root joints?

**Comment by ZhengdiYu** [comment]
> That's to say, whether or not use gt scale information to rescale the predict joints, you all use the MCP joint of the middle finger as root joints?

Sure, we follow the same protocol as prior works.

**Comment by julyiii** [comment]
OK，thank you for your reply!
