### ISSUE TITLE
How to get gt_segm?

### ISSUE THREAD

**Issue by luckyday2022** [ZhengdiYu/Arbitrary-Hands-3D-Reconstruction#18]

**Comment by ZhengdiYu** [comment]
Sorry for the delay in response. We use this [repo](https://github.com/zc-alexfan/render_mano_ih) to get gt_segm.

**Comment by luckyday2022** [comment]
Thank you for your response. May I ask if the training code for ACR will be released?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhengdiYu/Arbitrary-Hands-3D-Reconstruction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月1日(星期五) 晚上7:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZhengdiYu/Arbitrary-Hands-3D-Reconstruction] How to get gt_segm? (Issue #18)





 
Sorry for the delay in response. We use this repo to get gt_segm.
