### ISSUE TITLE
Parameters of 'kp3ds'

### ISSUE THREAD

**Issue by tkhkaeio** [ZhengdiYu/Arbitrary-Hands-3D-Reconstruction#19]
Thank you for offering the great baseline.

In the visualizer, the code has 3d keypoint visualization. 
Here the arguments are set as this, but I can't find how to create them. Please teach me.
`real_aligned, pred_aligned, pos3d_vis_mask, joint3d_bones = kwargs['kp3ds']`

**Comment by ZhengdiYu** [comment]
> Thank you for offering the great baseline.
> 
> In the visualizer, the code has 3d keypoint visualization. Here the arguments are set as this, but I can't find how to create them. Please teach me. `real_aligned, pred_aligned, pos3d_vis_mask, joint3d_bones = kwargs['kp3ds']`

Sorry for getting back late. I have omitted this in the simplified code. Basically, `real_aligned` and `pred_aligned ` are the gt 3d keypoints and the predicted 3d keypoints after root alignment, `pos3d_vis_mask` is also the GT valid mask for 3D.

I assume you are trying to visualize in-the-wild results, so you can simply pass `outputs['j3d']` as `pred_aligned` and remove `real_aligned` and set `pos3d_vis_mask` to always be 1. The bones should be the same as in 2d visualization as the order should be the same.
