### ISSUE TITLE
How to segment MANO hand

### ISSUE THREAD

**Issue by karta2155802** [ZhengdiYu/Arbitrary-Hands-3D-Reconstruction#3]
Hi, thanks for the remarkable work. The results are really impressive!!!
I'd like to know how to segment a mano hand to 16 parts. Could you provide the part information for the 778 vertices on both hands?
By the way, will you release the training code in the future?

**Comment by ZhengdiYu** [comment]
Thank you for your interest in our work!

We segment MANO hand by following [zc-alexfan](https://github.com/zc-alexfan/render_mano_ih). Thanks to their great code.

And yes, we will release the training code soon. We have been reconstructing a clean version for everyone to use with detailed instructions!
