### ISSUE TITLE
Reproduction of the Results on InterHand2.6M Dataset

### ISSUE THREAD

**Issue by jyunlee** [ZhengdiYu/Arbitrary-Hands-3D-Reconstruction#6]
First of all, thank you for your awesome work!
Also, thank you for kindly sharing your code and model weights to facilitate future research.

I'm currently working on a research project (which I'm targeting to submit in May) considering your work as one of the baseline methods.
However, I have been struggling with reproducing your results on InterHand2.6M dataset (as reported in the paper).
 
In the other thread, you mentioned that you used other extra in-the-wild datasets during training for the model weights currently shared in this repo.
So, I was wondering if you used different model weights (trained only on InterHand2.6M) when obtaining the InterHand2.6M results in the paper.
_**If so, would you kindly share the weights for InterHand2.6M dataset as well?**_

Thank you so much! 👍

**Comment by ZhengdiYu** [comment]
> First of all, thank you for your awesome work! Also, thank you for kindly sharing your code and model weights to facilitate future research.
> 
> I'm currently working on a research project (which I'm targeting to submit in May) considering your work as one of the baseline methods. However, I have been struggling with reproducing your results on InterHand2.6M dataset (as reported in the paper).
> 
> In the other thread, you mentioned that you used other extra in-the-wild datasets during training for the model weights currently shared in this repo. So, I was wondering if you used different model weights (trained only on InterHand2.6M) when obtaining the InterHand2.6M results in the paper. _**If so, would you kindly share the weights for InterHand2.6M dataset as well?**_
> 
> Thank you so much! 👍

Thank you so much for your interest in our work! :)

Yes, the current pre-trained weights are just used for the in-the-wild demo. 

Please rest assured, the training/eval code and weights will also be released together soon, after we restructure the code into this simple & clean version, hopefully before May!

**Comment by jyunlee** [comment]
Thank you so much! :)
Thank you again for your contribution to the community, and hope you have a nice day! 😄
