### ISSUE TITLE
Some questions...

### ISSUE THREAD

**Issue by Yamato-01** [ZhengdiYu/Arbitrary-Hands-3D-Reconstruction#7]
Wonderful work! I want to know whether ACR could handle some occasions such as only one hand in image well, such as only one hand in image. Because I notice that the `magic.jpg` in demo folder is one hand. But I get some confusing results using video input. I wonder if there are some other settings such as img resizing or cropping. Testing resolution is 1280×720.

**Comment by ZhengdiYu** [comment]
> Wonderful work! I want to know whether ACR could handle some occasions such as only one hand in image well, such as only one hand in image. Because I notice that the `magic.jpg` in demo folder is one hand. But I get some confusing results using video input. I wonder if there are some other settings such as img resizing or cropping. Testing resolution is 1280×720.

Thanks for your interest. 

1) Yes, ACR could work perfectly under the one-hand, hand-object interaction scenario as shown in the teaser gif in README.md and videos. 
2) Yes, all the input images are resized to 512x512 for batch processing and they maintain the same aspect ratio. Could you send or describe your 'confusing results' a bit more?

**Comment by Yamato-01** [comment]
Like this 
![image](https://user-images.githubusercontent.com/80616528/232735052-1d38f2bd-16d3-4113-9c41-b2d63c40d565.png)
![image](https://user-images.githubusercontent.com/80616528/232735173-4847703b-0444-433d-aacb-9f23aa683952.png)
It seems that detection meets something wrong

**Comment by ZhengdiYu** [comment]
> Like this ![image](https://user-images.githubusercontent.com/80616528/232735052-1d38f2bd-16d3-4113-9c41-b2d63c40d565.png) ![image](https://user-images.githubusercontent.com/80616528/232735173-4847703b-0444-433d-aacb-9f23aa683952.png) It seems that detection meets something wrong

This could happen when the `--centermap_conf_thresh` is a bit low. Please try to increase the threshold for detection. And please ensure to use the up-to-date pre-trained weights.

In the mean time, this looks unusual for a simple scene like this, could you maybe also send me the raw image or video? I could also try to re-produce your problem here.

**Comment by Yamato-01** [comment]
Thanks! I will change the threshold and try again.

**Comment by Yamato-01** [comment]
It seem increasing the threshold really work! But not for all images. Thanks a lot!
![image](https://user-images.githubusercontent.com/80616528/232741304-f519f376-f5f1-42f0-a7a4-8f2e48a435b0.png)
![image](https://user-images.githubusercontent.com/80616528/232741367-21c840ac-bb90-481c-8ca9-8933fab0be6d.png)
Are the two hand detections seperated? It seems that left hand mesh changes little between two images under different thresholds.

**Comment by ZhengdiYu** [comment]
> It seem increasing the threshold really work! But not for all images. Thanks a lot! ![image](https://user-images.githubusercontent.com/80616528/232741304-f519f376-f5f1-42f0-a7a4-8f2e48a435b0.png) ![image](https://user-images.githubusercontent.com/80616528/232741367-21c840ac-bb90-481c-8ca9-8933fab0be6d.png) Are the two hand detections seperated? It seems that left hand mesh changes little between two images under different thresholds.

I am glad to see that works. The reason for the changes should be that the cross-hand prior will be activated when there are two hands detected. In this case, where the right hand is actually missing, the accidently predicted right hand will somehow disturb the left hand's performance.

**Comment by Yamato-01** [comment]
I understand. Thanks!
