### ISSUE TITLE
what about the inference spped  

### ISSUE THREAD

**Issue by vicentowang** [ZhengdiYu/Arbitrary-Hands-3D-Reconstruction#8]
and when is the training code release.

**Comment by xungeer29** [comment]
18 FPS (GPU=2080)

**Comment by ZhengdiYu** [comment]
Sorry for the delay in response due to my work here. We will release the training code in the next two weeks. Thank you for your interest!

**Comment by xungeer29** [comment]
> Sorry for the delay in response due to my work here. We will release the training code in the next two weeks. Thank you for your interest!

One month has passed and we are still looking forward to your training code.
